---
abstract: 'Catalyst view to HTML::Zoom'
author:
  - 'Oliver Charles <oliver.g.charles@googlemail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100651'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-HTML-Zoom
requires:
  Catalyst::Runtime: 5.8
  HTML::Zoom: 0.9
  Method::Signatures::Simple: 0.05
  Moose: 0.98
  MooseX::Lexical::Types: 0.01
  MooseX::Types: 0.21
  MooseX::Types::Common: 0.001
  namespace::autoclean: 0.09
version: 0.001
